### ISSUE TITLE
Setting Up Your Conda Environment 

### ISSUE THREAD

**Issue by shreyabhadwal** [radlakha/AutoMLChurnPredict#8]
I understand that there are quite a few problems everyone is facing while setting up their Conda environment. I hope this information helps.  

I have committed an environment_droplet.yml file on my branch. Clone the repo and create a conda environment from it as follows:

`conda env create -f environment_droplet.yml
`

Please note that the first line of the yml file sets the new environment's name. Feel free to change your environment's name, mine is called env4. 

Don't forget to activate the conda environment using

`conda activate myenv`

You can verify that the new environment was set up correctly using 

`conda env list
`

Hope this helps.

**Comment by radlakha** [comment]
done.
